name: Update Production App Version

on:
  push:
    paths:
      - 'telegram-chatter/development/app-version.yaml'

jobs:
  update-production-version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Install hub
        run: |
          HUB_VERSION=2.14.2  # Adjust the version as needed
          HUB_OS=linux  # Adjust for other OS if needed
          HUB_ARCH=amd64  # Adjust for other architectures if needed
          
          curl -sSL "https://github.com/github/hub/releases/download/v${HUB_VERSION}/hub-${HUB_OS}-${HUB_ARCH}" -o /tmp/hub
          chmod +x /tmp/hub
          sudo mv /tmp/hub /usr/local/bin/hub
    
      - name: Create Pull Request
        id: pr
        run: |
          
          target_branch="main"
          
          git checkout -b update-production-version
          
          cp telegram-chatter/development/app-version.yaml telegram-chatter/production/app-version.yaml
          
          git add telegram-chatter/production/app-version.yaml
          
          git config --global user.email "luncanusergiu@gmail.com"
          git config --global user.name "SergiuLuncanu"
         
          git commit -m "Update production app version"
          git push origin update-production-version
          
          hub pull-request -b $target_branch -h update-production-version -m "Update production app version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
